version: '3'

services:
  server:
    container_name: server
    image: huriellopes/php-nginx
    tty: true
    stdin_open: true
    volumes:
      - ./:/app
    ports:
      - 80:80
    networks:
      - fiocruz_network

  database:
    container_name: db
    image: postgres:9.6
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "YOUR_PASSWORD"
      POSTGRES_DB: "DATABASE_NAME"
    restart: always
#    ports:
#      - 5432:5432
    networks:
      - fiocruz_network

networks:
  benfeitoria_network:
